CUSTOM_NAME=krx-pool-miner
CUSTOM_VERSION=v0.2.1-GPU-0.9-linux
CUSTOM_BUILD=1
CUSTOM_MINERBIN=keryx-miner
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/$CUSTOM_NAME/config.ini
CUSTOM_LOG_BASENAME=/var/log/miner/$CUSTOM_NAME/$CUSTOM_NAME
WEB_PORT=3338
