MINER_NAME=mc-miner
CUSTOM_NAME=$MINER_NAME
CUSTOM_VERSION=v0.2.1-GPU-0.10-linux
CUSTOM_BUILD=1
CUSTOM_MINERBIN=mc-miner
CUSTOM_CONFIG_FILENAME=config.ini
CUSTOM_LOG_BASENAME=/var/log/miner/custom/$MINER_NAME
WEB_PORT=3338
